create table sales_order_item(
item_id int(10) unsigned not null auto_increment primary key comment "Item Id",
order_id int(10) unsigned not null default 0,
parent_item_id int(10) unsigned,
quote_item_id int(10) unsigned,
store_id smallint(10) unsigned,
`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
 product_id int(10) unsigned,
  product_type varchar(255),
   product_options text,
   weight decimal(12,4) DEFAULT 0,
   is_virtual smallint(5) unsigned,
   sku varchar(255),
`name` varchar(255),
   description text,
   applied_rule_ids text,
   additional_data text,
   
   is_qty_decimal smallint(5) unsigned default 0,
      no_discount smallint(5) unsigned default 0,
      qty_backordered decimal(12,4) default 0,
	qty_canceled decimal(12,4) default 0,
      qty_invoiced decimal(12,4) default 0,
      qty_ordered decimal(12,4) default 0,
      qty_refunded decimal(12,4) default 0,
      qty_shipped decimal(12,4) default 0,
      base_cost decimal(12,4) default 0,
      price decimal(12,4) not null,
      base_price decimal(12,4) not null,
      original_price decimal(12,4) default 0,
      base_original_price decimal(12,4) default 0,
      tax_percent decimal(12,4) default 0,
      tax_amount decimal(12,4) default 0,
      foreign key(order_id) references sales_order(entity_id)
);